# Generated by Django 5.0.6 on 2024-08-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
