# Generated by Django 5.0.6 on 2024-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatparticipant',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
