# Generated by Django 5.0.6 on 2024-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatparticipant_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(blank=True, null=True, upload_to='dm_media'),
        ),
    ]
