# Generated by Django 5.0.6 on 2024-08-22 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_group_group_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_picture',
        ),
        migrations.CreateModel(
            name='groupprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_picture', models.ImageField(blank=True, null=True, upload_to='dm_media')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chats.group')),
            ],
        ),
    ]
