# Generated by Django 5.0.6 on 2024-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
